### ISSUE TITLE
Data Directory cannot be changed

### ISSUE THREAD

**Issue by Direcka** [ModRealms/ModRealmsLauncher#5]
**Precondition:** 
Open launcher settings
**Steps:**
1) Set Choose folder for data directory
2) Choose some folder
3) Save it

**Result:**
Directory remain unchanged
**Expectation**
Directory will be chanded to seted up directory

**Comment by GeekCornerGH** [comment]
I agree, this isnt working too for me

**Comment by TheFlash787** [comment]
Apologies for the delay in responding, this has since been fixed.
