### ISSUE TITLE
Settings in modpack reset after every start

### ISSUE THREAD

**Issue by Direcka** [ModRealms/ModRealmsLauncher#6]
**Precondition:**
Open launcher settings and start modpack (tested on chroma technology)
**Steps:**
Change any mod related setting 
Examples: Better fps algorytm, draconic evolution GUI position, Simpli Jentpack Gui possition
Exit the game
Run it again
**Result**
All no vanila settings reseted to default
**Expectation**
Settings will be stored

**Comment by TheFlash787** [comment]
Thanks for this Direcka! This has now been resolved for the next pack update.

**Comment by FooterMan14** [comment]
Unfortunately this issue has arisin once again. When you next load the launcher after changing some settings like shaders and resource packs they reset back to off.
